services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./output:/app/output  # Mount a volume for output files
    ports:
      - "5000:5000"
    networks:
      - app-network
  
  frontend:
    image: nginx:alpine
    volumes:
      - ./Frontend:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge